// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD049Pk3pHEWOb9DFEv4LTMo8xPwY0VMWc',
    appId: '1:391289284118:web:79cc95521664aaae2d3737',
    messagingSenderId: '391289284118',
    projectId: 'smart-chef-7c8d6',
    authDomain: 'smart-chef-7c8d6.firebaseapp.com',
    storageBucket: 'smart-chef-7c8d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK4gP_lo0aTiwjf5SvHZ79yijstMEn5Hw',
    appId: '1:391289284118:android:44fa9e75357500d82d3737',
    messagingSenderId: '391289284118',
    projectId: 'smart-chef-7c8d6',
    storageBucket: 'smart-chef-7c8d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8PyiVdPdyn0sE8GdII8Lu2O6_M2H2MZ8',
    appId: '1:391289284118:ios:ad60cbac37846b712d3737',
    messagingSenderId: '391289284118',
    projectId: 'smart-chef-7c8d6',
    storageBucket: 'smart-chef-7c8d6.firebasestorage.app',
    androidClientId: '391289284118-8bts0tgc4lok6ufusdavavu54pjlm5mj.apps.googleusercontent.com',
    iosClientId: '391289284118-evvo074tqbn8uq32on7njm551sgahmdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartChef',
  );
}
